export default {
  //Icons
  home: require('../assets/icon/home.png'),
  pulse: require('../assets/icon/pulse.png'),
  bell: require('../assets/icon/bell.png'),
  heart: require('../assets/icon/heart.png'),
  settings: require('../assets/icon/settings.png'),
  palm: require('../assets/icon/palm.png'),
  pill: require('../assets/icon/pill.png'),
  smartWatch: require('../assets/icon/smartWatch.png'),
  heartBeat: require('../assets/icon/heartBeat.png'),
  adults: require('../assets/icon/adults.png'),
  scanLine: require('../assets/icon/scanLine.png'),
  leftArrow: require('../assets/icon/leftArrow.png'),
  calendar: require('../assets/icon/calendar.png'),
  downArrow: require('../assets/icon/downArrow.png'),
  upArrow: require('../assets/icon/upArrow.png'),
  dots: require('../assets/icon/dots.png'),
  drop:require('../assets/icon/drop.png'),
  plus:require('../assets/icon/plus.png'),
  document:require('../assets/icon/document.png'),
  location:require('../assets/icon/location.png'),
  gallery:require('../assets/icon/gallery.png'),
  lock:require('../assets/icon/lock.png'),
  upload:require('../assets/icon/upload.png'),
  correct:require('../assets/icon/correct.png'),
  rightArrow:require('../assets/icon/rightArrow.png'),
  chartDown:require('../assets/icon/chartDown.png'),
  chartUp:require('../assets/icon/chartUp.png'),
  horizontalLine:require('../assets/icon/horizontalLine.png'),
  lab:require('../assets/icon/lab.png'),
  stethoscope:require('../assets/icon/stethoscope.png'),
  clock:require('../assets/icon/clock.png'),
  sortDownArrow:require('../assets/icon/sortDownArrow.png'),
  //Images
  logo: require('../assets/image/logo.png'),
  reminder: require('../assets/image/reminder.png'),
  darkMode: require('../assets/image/darkMode.png'),
  lightMode: require('../assets/image/lightMode.png'),

  //Videos
  splashVideo: require('../assets/video/SplashVideo.mp4'),
};
